import fs from 'fs';
import path from 'path';

const root = path.resolve(process.cwd());
const maps = JSON.parse(fs.readFileSync(path.join(root, 'data/maps/zones.json'), 'utf8'));
const quests = JSON.parse(fs.readFileSync(path.join(root, 'data/quests/quests.json'), 'utf8'));
const dialogues = JSON.parse(fs.readFileSync(path.join(root, 'data/dialogues/dialogues.json'), 'utf8'));

const outDir = path.join(root, 'generated');
fs.mkdirSync(outDir, { recursive: true });

const missionFlags = quests.missions.map((m) => m.setFlag);
const allZones = maps.zones.map((z) => z.id);

const constantsFlags = [
  '/* Auto-generated by scripts/generate_pokeemerald_skeleton.mjs */',
  '#ifndef GUARD_CONSTANTS_CLEVERMAX_FLAGS_H',
  '#define GUARD_CONSTANTS_CLEVERMAX_FLAGS_H',
  '',
  '// Reserve an appropriate block in your constants/flags.h',
  '// and replace placeholders with real numeric values.',
  ...missionFlags.map((f, i) => `#define ${f} (FLAG_CUSTOM_START + ${i})`),
  '',
  '#endif // GUARD_CONSTANTS_CLEVERMAX_FLAGS_H',
  ''
].join('\n');

const missionTable = [
  '/* Auto-generated mission list */',
  '#ifndef GUARD_CLEVERMAX_MISSIONS_H',
  '#define GUARD_CLEVERMAX_MISSIONS_H',
  '',
  'struct CleverMaxMissionDef',
  '{',
  '    const u8 *title;',
  '    u16 completionFlag;',
  '};',
  '',
  ...quests.missions.map((m, i) => `#define CM_MISSION_ID_${i + 1} ${i + 1}`),
  '#define CM_MISSION_COUNT ' + quests.missions.length,
  '',
  '#endif // GUARD_CLEVERMAX_MISSIONS_H',
  ''
].join('\n');

const missionStrings = [
  '/* Auto-generated strings skeleton */',
  '#ifndef GUARD_CLEVERMAX_STRINGS_H',
  '#define GUARD_CLEVERMAX_STRINGS_H',
  '',
  ...quests.missions.map((m, i) => `static const u8 sCleverMaxMissionTitle${i + 1}[] = _("${sanitize(m.title)}");`),
  '',
  '#endif // GUARD_CLEVERMAX_STRINGS_H',
  ''
].join('\n');

const zoneWarps = [
  '/* Auto-generated warp routing reference */',
  '# CleverMax Zone Routing',
  '',
  ...maps.zones.map((z) => {
    const lines = [`[${z.id}] ${z.displayName}`];
    if (!z.warps || z.warps.length === 0) {
      lines.push('- (no outgoing warps)');
    } else {
      for (const w of z.warps) {
        lines.push(`- (${w.x},${w.y}) -> ${w.to}${w.requiresFlag ? ` [requires ${w.requiresFlag}]` : ''}`);
      }
    }
    return lines.join('\n');
  }),
  ''
].join('\n');

const dialogueScripts = [
  '/* Auto-generated dialogue script skeleton */',
  '#include "global.h"',
  '#include "event_data.h"',
  '#include "constants/flags.h"',
  '',
  ...Object.entries(dialogues).flatMap(([npcId, lines], idx) => {
    const label = `CleverMax_${npcId}_Text`;
    const script = `CleverMax_${npcId}_Script`;
    const parts = [];
    parts.push(`${label}:`);
    parts.push(`    .string "${sanitize(lines.join(' '))}$"`);
    parts.push('');
    parts.push(`${script}:`);
    parts.push('    lock');
    parts.push(`    msgbox ${label}, MSGBOX_DEFAULT`);
    const mission = quests.missions.find((m) => linksNpcToMission(npcId, m));
    if (mission) parts.push(`    setflag ${mission.setFlag}`);
    parts.push('    release');
    parts.push('    end');
    parts.push('');
    return parts;
  })
].join('\n');

const zoneMetaTable = [
  '/* Auto-generated map metadata seed */',
  '#ifndef GUARD_CLEVERMAX_MAP_META_H',
  '#define GUARD_CLEVERMAX_MAP_META_H',
  '',
  'struct CleverMaxZoneMeta',
  '{',
  '    const u8 *mapName;',
  '    u8 order;',
  '};',
  '',
  ...allZones.map((z, i) => `#define CM_ZONE_${z} ${i + 1}`),
  '#define CM_ZONE_COUNT ' + allZones.length,
  '',
  '#endif // GUARD_CLEVERMAX_MAP_META_H',
  ''
].join('\n');

fs.writeFileSync(path.join(outDir, 'clevermax_flags.h'), constantsFlags);
fs.writeFileSync(path.join(outDir, 'clevermax_missions.h'), missionTable);
fs.writeFileSync(path.join(outDir, 'clevermax_strings.h'), missionStrings);
fs.writeFileSync(path.join(outDir, 'clevermax_warp_routing.md'), zoneWarps);
fs.writeFileSync(path.join(outDir, 'clevermax_dialogue_scripts.inc'), dialogueScripts);
fs.writeFileSync(path.join(outDir, 'clevermax_map_meta.h'), zoneMetaTable);

const manifest = {
  generatedAt: new Date().toISOString(),
  files: [
    'clevermax_flags.h',
    'clevermax_missions.h',
    'clevermax_strings.h',
    'clevermax_warp_routing.md',
    'clevermax_dialogue_scripts.inc',
    'clevermax_map_meta.h'
  ],
  source: {
    maps: 'data/maps/zones.json',
    quests: 'data/quests/quests.json',
    dialogues: 'data/dialogues/dialogues.json'
  }
};

fs.writeFileSync(path.join(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2));

console.log('Generated files in', outDir);

function sanitize(s) {
  return String(s)
    .replace(/[\n\r]+/g, ' ')
    .replace(/"/g, '\\"')
    .replace(/[^\x20-\x7E]/g, '');
}

function linksNpcToMission(npcId, mission) {
  if (npcId.includes('SAILOR') && mission.id.includes('05_WIFI')) return true;
  if (npcId.includes('STUDENT') && mission.id.includes('03_ACCESS')) return true;
  if (npcId.includes('MERCHANT') && mission.id.includes('02_SOCIAL')) return true;
  if (npcId.includes('RC_BRIEF') && mission.id.includes('01_PHISHING')) return true;
  if (npcId.includes('RC_FINAL') && mission.id.includes('08_FINAL_DEFENSE')) return true;
  return false;
}
